/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.3 appleWatchUltra.gltf
Author: polyman (https://sketchfab.com/ely.haddad)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/watch-ultra-i-alpine-loop-orange-d5e801a58fb24af6a4bf7d433eeca04b
Title: Watch Ultra I Alpine Loop Orange
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function AppleWatchUltra(props) {
  const { nodes, materials } = useGLTF('/apple_watch_ultra/AppleWatchUltra.gltf')
  return (
    <group {...props} dispose={null}>
      <group scale={8}>
        <mesh geometry={nodes.PPhvAUHUGzJYMhL.geometry} material={materials.DpfyoSSiSSiguqV} />
        <mesh geometry={nodes.LWVGlhvktNPWDmu.geometry} material={materials.hlaWqbXPxAbQzbJ} />
        <mesh geometry={nodes.eXUJdTIAeUGmQLZ.geometry} material={materials.YWfwokrwvbztRbo} />
        <mesh geometry={nodes.khaHlXdxjItYhNs.geometry} material={materials.JhVSDiADFtJHFLa} />
        <mesh geometry={nodes.DpLeqowIFgYtGjG.geometry} material={materials.lokMFBOdPtkNVUL} />
        <mesh geometry={nodes.lTuqHocPHeeYuLO.geometry} material={materials.cEvUsXxsuGocZLw} />
        <mesh geometry={nodes.qfqlcqjRdzzVekA.geometry} material={materials.YWfwokrwvbztRbo} />
        <mesh geometry={nodes.vWfihlqoNhaJTLj.geometry} material={materials.initialShadingGroup} />
        <mesh geometry={nodes.KZLnjqsQgoygPoi.geometry} material={materials.WqlRgaclVpXEtLR} />
        <mesh geometry={nodes.wMgdGPGcmgrPUeE.geometry} material={materials.DpfyoSSiSSiguqV} />
        <mesh geometry={nodes.yPaUlGyzZhvStMM.geometry} material={materials.DpfyoSSiSSiguqV} />
        <mesh geometry={nodes.XYTcEkWJWbbjayl.geometry} material={materials.DpfyoSSiSSiguqV} />
        <mesh geometry={nodes.yXwlQnMKInchVwb.geometry} material={materials.WqlRgaclVpXEtLR} />
        <mesh geometry={nodes.BDhXHhWQPzbsApC.geometry} material={materials.OraiDWpYBKrUaVi} />
        <mesh geometry={nodes.ARsYRDtRfaqRvjc.geometry} material={materials.RLtPucjBYpWldMw} />
        <mesh geometry={nodes.dEgYDFMHfbkpmEF.geometry} material={materials.vAAmUmRloGrqeoZ} />
        <mesh geometry={nodes.sYBCdasHzmkyDRS.geometry} material={materials.DpfyoSSiSSiguqV} />
        <mesh geometry={nodes.slfmzSCVEebgEnx.geometry} material={materials.vAAmUmRloGrqeoZ} />
        <mesh geometry={nodes.cUdLcKThVrgrQtG.geometry} material={materials.hgluOErnmhtiUYN} />
        <mesh geometry={nodes.dApvNLhuSmTYFHU.geometry} material={materials.cEvUsXxsuGocZLw} />
        <mesh geometry={nodes.dDmAxNyjhIDOSOh.geometry} material={materials.FWVZLUbBnucfoaf} />
        <mesh geometry={nodes.uwsZHcLJnpKqEWY.geometry} material={materials.WNpOSdXcedsiIxb} />
        <mesh geometry={nodes.usBhaSMGegdgFZD.geometry} material={materials.DpfyoSSiSSiguqV} />
        <mesh geometry={nodes.TgXjmfNiJNmBEaf.geometry} material={materials.WTIUJKaXCMoeXRu} />
        <mesh geometry={nodes.oNBZPqvuuOZaMJD.geometry} material={materials.ZaRnLYKTtVDoxDv} />
        <mesh geometry={nodes.ukHQvPcopDbGAeP.geometry} material={materials.kCssvzrClyGUQkQ} />
        <mesh geometry={nodes.wlIPQLVNyFEOcyR.geometry} material={materials.kCssvzrClyGUQkQ} />
        <mesh geometry={nodes.IXiSHYGuoMgcNgF.geometry} material={materials.XrFeyJHNdKUjpKu} />
        <mesh geometry={nodes.dutMHxWYxKkWoIl.geometry} material={materials.ytyYsmKHSFPTRzX} />
        <mesh geometry={nodes.vaRMlNGtRRowtqF.geometry} material={materials.CpdaRQhrDwkjJvt} />
        <mesh geometry={nodes.PTPnChoGCzenuOx.geometry} material={materials.PZbVgVTNgRssNlb} />
        <mesh geometry={nodes.KsxIrenucRYdQlx.geometry} material={materials.FNPDFKuVXKOlvzh} />
        <mesh geometry={nodes.fCkJQDPNwsNBzWm.geometry} material={materials.XPzMameFUCFBvNY} />
        <mesh geometry={nodes.scpcAfQFCzMwocy.geometry} material={materials.nwKRBiBrdJBKTDX} />
        <mesh geometry={nodes.YbfvuZWRqXlvTkW.geometry} material={materials.YWfwokrwvbztRbo} />
        <mesh geometry={nodes.wmnqxNpNCdRfDfA.geometry} material={materials.UlFjqascpPnJnyb} />
        <mesh geometry={nodes.SAesXTqirPZWRXc.geometry} material={materials.LMNEMIqLLSofXax} />
        <mesh geometry={nodes.uFzdsQxnXjPAlfo.geometry} material={materials.DpfyoSSiSSiguqV} />
        <mesh geometry={nodes.vdoUifIjrUGtLiS.geometry} material={materials.DpfyoSSiSSiguqV} />
        <mesh geometry={nodes.DPJxFEyTsdtZHfm.geometry} material={materials.DpfyoSSiSSiguqV} />
        <mesh geometry={nodes.DmhCzDQXADCcXPt.geometry} material={materials.RZAUBIkSLvyIlJf} />
        <mesh geometry={nodes.cYPgdqcCkfmEnrF.geometry} material={materials.ObrQaHSLRyNZejZ} />
        <mesh geometry={nodes.yFPJxjHCZaMTTSP.geometry} material={materials.PwlvrZKCtsfdXgk} />
        <mesh geometry={nodes.hFurRdLJljkLFkB.geometry} material={materials.zWSbkmvYqArUSOM} />
      </group>
    </group>
  )
}

useGLTF.preload('/apple_watch_ultra/AppleWatchUltra.gltf')
